// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos/ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // MUST CONTAIN VALID WEB KEYS
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR3f5SniqMmjAmFuODa0GplwBRYcB1fJY',
    appId: '1:262205640310:web:346a10a2f78b4eb7ad5957',
    messagingSenderId: '262205640310',
    projectId: 'app-watchhub-08',
    authDomain: 'app-watchhub-08.firebaseapp.com',
    storageBucket: 'app-watchhub-08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEDNFREP1q46GxAEQkGPsoMBKQ1XOIeVM',
    appId: '1:262205640310:android:ce9fa44a31ce65e6ad5957',
    messagingSenderId: '262205640310',
    projectId: 'app-watchhub-08',
    storageBucket: 'app-watchhub-08.firebasestorage.app',
  );
}
